### First Evaluation

In [1]:
import json

with open("ragas_prep.json", "r") as f:
    file_loaded = json.load(f)

print(len(file_loaded))

28

In [2]:
n = 3
batches = [file_loaded[i: i+n] for i in range(0, len(file_loaded), n)]

### First batch of eval dataset

In [3]:
import sys
import os

absolute_path = os.path.abspath("..")

if absolute_path not in sys.path:
    sys.path.append(absolute_path)

from evaluation.ragas_eval import Ragged

ragger = Ragged(
    dataset=batches[0]
)

ragger.score()

/home/sudip/Desktop/perplex_city/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/sudip/Desktop/perplex_city/.venv/lib/python3.11/site-packages/instructor/providers/gemini/client.py:5: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai  # type: ignore[import-not-found]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 19380.20it/s]
BertModel LOAD REPORT from: thenlper/gte-small
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  58%|█████▊    | 7/12 [01:23<00:43,  8.80s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 12/12 [02:40<00:00, 13.37s/it]

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,Who is the current Secretary-General of the Un...,[Secretary-General of the United Nations\n| Se...,The current Secretary-General of the United Na...,António Guterres is the Secretary-General of t...,0.750000,1.000000,0.333333,1.0
1,Which company currently has the largest market...,[This is the list of the world's biggest compa...,"As of December 31, 2025, Apple has the largest...",NVIDIA Corporation has recently ranked as one ...,0.000000,0.967235,0.000000,0.0
2,What are the main symptoms of dengue fever?,[Symptoms · Severe stomach pain · Persistent v...,Dengue fever can manifest with a variety of sy...,"Dengue fever commonly causes high fever, sever...",0.961538,0.995438,0.500000,1.0

### Second batch

In [3]:
import sys
import os

absolute_path = os.path.abspath("..")

if absolute_path not in sys.path:
    sys.path.append(absolute_path)

from evaluation.ragas_eval import Ragged

ragger = Ragged(
    dataset=batches[1]
)

ragger.score()

/home/sudip/Desktop/perplex_city/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/sudip/Desktop/perplex_city/.venv/lib/python3.11/site-packages/instructor/providers/gemini/client.py:5: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai  # type: ignore[import-not-found]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3636.08it/s]
BertModel LOAD REPORT from: thenlper/gte-small
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 12/12 [02:51<00:00, 14.28s/it]

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,Who wrote the novel 'One Hundred Years of Soli...,[Gabriel García Márquez\nGabriel García Márque...,The novel 'One Hundred Years of Solitude' was ...,Gabriel García Márquez wrote 'One Hundred Year...,0.000000,0.999204,1.000000,0.0
1,What is the latest version of Python currently...,[Status of Python versions¶\nThe main\nbranch ...,"The main branch, which is currently the future...",The latest stable version of Python is Python ...,1.000000,0.930939,0.000000,0.0
2,Which country has won the most Olympic gold me...,[All-time Olympic Games medal table\n| Olympic...,"I am sorry, but the provided context does not ...",The United States has won the most Olympic gol...,0.666667,0.000000,0.333333,1.0

### Third batch

In [4]:
import sys
import os

absolute_path = os.path.abspath("..")

if absolute_path not in sys.path:
    sys.path.append(absolute_path)

from evaluation.ragas_eval import Ragged

ragger = Ragged(
    dataset=batches[2]
)

ragger.score()

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 18228.54it/s]
BertModel LOAD REPORT from: thenlper/gte-small
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   8%|▊         | 1/12 [00:00<00:08,  1.31it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 12/12 [02:12<00:00, 11.03s/it]

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,Which programming language is primarily used f...,"[If you want to build apps for iPhones, you sh...",Swift is the preferred and official programmin...,Swift is the primary programming language used...,0.400000,0.933499,1.0,1.0
1,What are the admission requirements for intern...,[Admission requirements for students who have ...,International students applying to the Univers...,International students generally need a recogn...,0.066667,0.968313,1.0,1.0
2,Which country has a higher GDP per capita toda...,[GDP per capita (current US$) - JapanCountry o...,"The country where Toyota was founded, Japan, h...",South Korea (Samsung) generally has a higher G...,0.000000,0.893033,0.0,0.0

### Expanding user queries

In [1]:
import os
import sys

current = os.path.abspath("..")

if current not in sys.path:
    sys.path.append(current)

from pipeline.query_expander import QueryExpander

expander = QueryExpander()

expander.expanded_queries("What was the reason of Gen Z protest in Nepal?")

['Gen Z protest Nepal reasons',
 'Nepal youth activism causes 2024',
 'Social movements Nepal Gen Z',
 'Political engagement Nepal young adults',
 'Demographic trends Nepal protests']

In [2]:
expander.expanded_queries("Which company currently has the largest market capitalization in the world?")

['largest market capitalization company world 2026-05-12',
 'top 5 market cap companies world 2026-05-12',
 'market capitalization trends largest companies 2026']

In [3]:
expander.expanded_queries("Who wrote the novel 'One Hundred Years of Solitude'?")

['FACTUAL',
 {'question1': "author of 'One Hundred Years of Solitude'",
  'question2': "'One Hundred Years of Solitude' publication date",
  'question3': 'Gabriel Garcia Marquez bibliography',
  'question4': "literary significance of 'One Hundred Years of Solitude'",
  'question5': "translations of 'One Hundred Years of Solitude'"}]

In [4]:
expander.expanded_queries("Which country has a higher GDP per capita today: the country where Toyota was founded or the country where Samsung is headquartered?")

['MULTIFACETED/COMPARISON',
 {'question1': 'GDP per capita Japan 2026',
  'question2': 'GDP per capita South Korea 2026',
  'question3': 'Toyota founding country',
  'question4': 'Samsung headquarters country',
  'question5': None}]